### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/nuntius-bot#17]
We need to tests:
* [ ] ~~Check events~~
* [x] Check entity layer - will check the entity manager (#34)
* [x] Check tasks - will check the tasks manager as well (#33)
* [x] Check the update manager (#35)
